name: chimera

channels:
  - defaults

dependencies:
  - Flask>=1.0
  - Jinja2>=2.10.1
  - MarkupSafe
  - pandas
  - pytest
  - python=3.7
  - pip:
    - coveralls
    - pytest-cov
    - seqlogo
    - weblogo==3.6.0
