name: chimera

channels:
  - defaults

dependencies:
  - biopython
  - Flask>=1.0
  - Jinja2>=2.10.1
  - MarkupSafe
  - matplotlib
  - pandas
  - pip>=19.0.3
  - pytest
  - python=3.7
  - tqdm
  - pip:
    - coveralls
    - prody
    - pytest-cov
    - weblogo
