name: chimera

channels:
  - defaults

dependencies:
  - biopython
  - Flask>=1.0
  - Jinja2>=2.10.1
  - MarkupSafe
  - matplotlib
  - pandas=0.24.2
  - pip
  - pytest
  - python=3.7
  - tqdm=4.31.1
  - pip:
    - celery
    - coveralls
    - plotly
    - prody
    - pytest-cov
    - redis
    - smart_open
    - weblogo
